---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: test-operator
  namespace: openstack
spec:
  name: test-operator
  source: test-operator-catalog
  sourceNamespace: openstack
